name       : kbackup
version    : 21.12.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kbackup-21.12.0.tar.xz : b5d0829609b6f88a5d51f874b95a72aeac8162e84c5ec93d4bf5b08ac23328ce
homepage   : https://apps.kde.org/en/kbackup
license    : GPL-2.0-or-later
component  : network.util
summary    : KBackup is an application which lets you back up your data in a simple, user friendly way
description: |
    KBackup is an application which lets you back up your data in a simple, user friendly way
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kio-devel
    - kiconthemes-devel
    - kguiaddons-devel
    - knotifications-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
