name       : kbackup
version    : 22.08.3
release    : 16
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kbackup-22.08.3.tar.xz : bce35c66c97b813fa01dbc3b21e5ec6d9d6b2d4315adcdacee44007c2da1cb9b
homepage   : https://apps.kde.org/en/kbackup
license    : GPL-2.0-or-later
component  : network.util
summary    : KBackup is an application which lets you back up your data in a simple, user friendly way
description: |
    KBackup is an application which lets you back up your data in a simple, user friendly way
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kio-devel
    - kiconthemes-devel
    - kguiaddons-devel
    - knotifications-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
